name: CI|CD Deploy docs
permissions:
    contents: write
on:
    push:
        tags:
            - v*

jobs:
    build:
        name: build vite press
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash

        if: startsWith(github.ref, 'refs/tags/')
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]

        steps:
            -   name: è¯»å–ä»“åº“å†…å®¹ ğŸ‘“
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: è®¾ç½® Node.js ğŸ¶
                uses: actions/setup-node@v4
                with:
                    node-version: 20

            -   name: å®‰è£… yarn ğŸ¸
                run: npm install --global yarn

            -   name: æ„å»ºæ–‡æ¡£ ğŸ”¨
                env:
                    NODE_OPTIONS: --max_old_space_size=8192
                run: |-
                    yarn install
                    yarn run docs:build

            -   name: éƒ¨ç½²æ–‡æ¡£ ğŸ‘Œ
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    branch: pages
                    folder: docs/.vitepress/dist